spring.datasource.url=jdbc:sqlite:/Users/p/Development/Wardrobe/my_closet.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.datasource.hikari.connection-properties=date_class=TEXT,date_format=yyyy-MM-dd
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys = ON;

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
